todoApp/data/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('update/<str:pk>/', views.update, name='update'),
    path('delete/<str:pk>', views.delete, name='delete')
]

todoApp/todoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data.urls'))
]

todoApp/data/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

todoApp/data/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

todoApp/data/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.

from .models import *
from .forms import *


def index(request):
    tasks = Task.objects.all()
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    context = {'tasks': tasks, 'form': form}
    return render(request, 'tasks/index.html', context)


def update(request, pk):
    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form': form}
    return render(request, 'tasks/update.html', context)


def delete(request, pk):
    item = Task.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        return redirect('/')

    context = {'item': item}

    return render(request, 'tasks/delete.html', context)

todoApp/data/templates/tasks/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <style>
        body{
            margin: 5%;
        }
        h1{
            margin-bottom: 2rem;
        }
        span{
            color: red;
        }
        .button{
            font-size:24px;
            width: 10rem;
            color: white;
            background-color: black;
            border: 2px solid transparent;
            margin-top: 25px;
        }
        form{
            display: inline;
        }
        .delete{
            font-size:24px;
            width: 10rem;
            color: red;
            background-color: white;
            border: 2px solid red;
        }
        button a {
            text-decoration: none;
            color: white;
        }
    </style>
</head>
<body>
    <h1>Delete</h1>
    <h3>Are you sure you want to delete <span> '{{item}}' </span> ?</h3>
    <form action="" method="POST">
        {% csrf_token %}
        <button class="delete" type='submit'>Delete</button>
    </form>
    <button class="button"><a href="{% url 'index' %}">No</a></button>

</body>
</html>

todoApp/data/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo app</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <style>
        body{
            margin: 5%;
        }
        .heading{
            margin-bottom: 2rem;
        }
        input[name="title"] {
            display: inline-block;
            width: 25rem;
            margin-right: -8px;
            font-size:24px;
            border: 2px solid #D0D0D0;
            background-color: #D0D0D0;
        }
        .button{
            display: inline-block;
            font-size:24px;
            width: 10rem;
            color: white;
            background-color: black;
            border: 2px solid transparent;
        }
        .top-level{
            margin-top: 2rem;
        }
        .task{
            font-size: 24px;
            margin-top: 1rem;
            background-color: #D0D0D0;
            border-right: 4px solid black;
        }
        a{
            float: right;
            margin-right: 10px;
        }
        strike, span{
            background-color: #D0D0D0;
        }
    </style>
</head>
<body>
    <h1 class="heading">Todo App</h1>

    <form method="POST" action="/" autocomplete="off">
        {% csrf_token %}
        {{form.title}}
        <button class="button" type='submit'>Add Task</button>
    </form>
    <div class="top-level row col-lg-12">
        {% for task in tasks %}
        <div class="task col-lg-4">
            {% if task.complete == True %}
            <strike>{{task}}</strike>
            {% else %}
            <span>{{task}}</span>
            {% endif %}
            <a href="{% url 'update' task.id %}"><i style="color: forestgreen;" class="far fa-edit"></i></a>
            <a href="{% url 'delete' task.id %}"><i style="color: red;" class="far fa-trash-alt"></i></a>
        </div>
        {% endfor %}
    </div>
</body>
</html>

todoApp/data/templates/tasks/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <style>
        body{
            margin: 5%;
        }
        h1{
            margin-bottom: 2rem;
        }
        label{
            font-size: 24px;
            margin-right: 15px;
        }
        .button{
            display: inline-block;
            font-size:24px;
            width: 10rem;
            color: white;
            background-color: black;
            border: 2px solid transparent;
            margin-left: 35px;
        }
        input[name='complete']{
            height: 20px;
            width: 20px;
        }
        input[name='title']{
            font-size: 20px;
        }
        label[for='id_complete']{
            margin-left: 25px;
        }
    </style>
</head>
<body>
    <h1>Update Item</h1>

    <form action="" method="POST"> {% csrf_token %}
        {{form}}
        <button class="button" type='submit'>Update Task</button>
    </form>
</body>
</html>